In [13]:
import requests
import json
import pandas as pd

In [14]:
YOUR_API_KEY = "d1138da0-c7d4-4f81-a2c6-44de7bbd80a0"

In [15]:
url = "https://api.openchargemap.io/v3/poi/"

params_base = {
    "output": "json",
    "maxresults": 10000, 
    "compact": "true", 
    "verbose": "false", 
    "key": "d1138da0-c7d4-4f81-a2c6-44de7bbd80a0"

}

country_codes = ["ES", "FR"]

data_country = []

for country in country_codes:
    params = params_base.copy()
    params["countrycode"] = country
    
    response = requests.get(url, params=params)

    if response.status_code == 200:
       data = response.json()  
       data_country.extend(data)
    else:
        print(f"Error en la solicitud para {country}: {response.status_code}")
    
data_chargesmap= pd.DataFrame(data_country)

In [16]:
print(data_chargesmap.head(10))
print("Columnas en el DataFrame:", data_chargesmap.columns)

   IsRecentlyVerified      DateLastVerified      ID  \
0                True  2024-10-31T10:57:00Z  305793
1                True  2024-10-31T10:29:00Z  305791
2                True  2024-10-31T10:25:00Z  305790
3                True  2024-10-31T10:23:00Z  305789
4                True  2024-10-31T10:23:00Z  305788
5                True  2024-10-31T10:18:00Z  305787
6                True  2024-10-31T07:15:00Z  305785
7                True  2024-10-30T19:57:00Z  305784
8                True  2024-10-30T19:53:00Z  305783
9                True  2024-10-30T19:52:00Z  305782

                                   UUID  DataProviderID  OperatorID  \
0  9F6D0CBB-087F-4263-9CF2-D78E4EFA6E0A               1        45.0
1  8120149D-2C43-42F0-85F3-17240E5A760D               1         1.0
2  4A210801-73B5-416D-A32B-56E6D638A142               1         1.0
3  AA61D61E-8DD1-4ACC-8497-7622B965DC5C               1         1.0
4  A65E27CE-36CB-410A-922A-D0DF6534BD30               1         1.0
5  30001948-0CA9-4E19-8143-6E8A2D4AABDA               1         1.0
6  0F9F3879-8DE6-4B0E-817A-D09607F796C5               1       207.0
7  33A3D719-A644-49A0-A1EA-B82A090F4A17               1        45.0
8  6B6006CD-D93D-469D-9278-A6F2C11F4F83               1         1.0
9  BD82D54E-AE15-4DDE-95A0-DFC24BC90CF6               1      3275.0

   UsageTypeID                   UsageCost  \
0          5.0                    1,7€/kWh
1          1.0
2          1.0
3          1.0
4          1.0
5          1.0
6          4.0  0,39€/kWh AC + parking fee
7          6.0                   0,25€/kWh
8          1.0
9          6.0                         NaN

                                         AddressInfo  \
0  {'ID': 306182, 'Title': 'Padle Madrid Las Tabl...
1  {'ID': 306180, 'Title': 'Ayunt. Yaiza. Uga. Ca...
2  {'ID': 306179, 'Title': 'Ayunt. Yaiza. Calle P...
3  {'ID': 306178, 'Title': 'Ayunt. Yaiza. Calle J...
4  {'ID': 306177, 'Title': 'Ayunt. Yaiza. Calle M...
5  {'ID': 306176, 'Title': 'Ayunt. Yaiza. Calle L...
6  {'ID': 306174, 'Title': 'Parking La Mota Vieja...
7  {'ID': 306173, 'Title': 'Rest. Hotel La Parada...
8  {'ID': 306172, 'Title': 'Gumiel de Izán', 'Add...
9  {'ID': 306171, 'Title': 'Renault Aranda de Due...

                                         Connections  NumberOfPoints  \
0  [{'ID': 578690, 'ConnectionTypeID': 25, 'Statu...             2.0
1  [{'ID': 578688, 'ConnectionTypeID': 25, 'Statu...             2.0
2  [{'ID': 578687, 'ConnectionTypeID': 25, 'Statu...             2.0
3  [{'ID': 578686, 'ConnectionTypeID': 25, 'Statu...             2.0
4  [{'ID': 578685, 'ConnectionTypeID': 25, 'Statu...             2.0
5  [{'ID': 578684, 'ConnectionTypeID': 25, 'Statu...             2.0
6  [{'ID': 578677, 'ConnectionTypeID': 25, 'Statu...             8.0
7  [{'ID': 578676, 'ConnectionTypeID': 25, 'Statu...             1.0
8  [{'ID': 578675, 'ConnectionTypeID': 25, 'Statu...             1.0
9  [{'ID': 578674, 'ConnectionTypeID': 25, 'Statu...             2.0

   StatusTypeID  DateLastStatusUpdate  DataQualityLevel           DateCreated  \
0            50  2024-10-31T10:57:00Z                 1  2024-10-31T10:57:00Z
1           150  2024-10-31T10:29:00Z                 1  2024-10-31T10:29:00Z
2           150  2024-10-31T10:25:00Z                 1  2024-10-31T10:25:00Z
3           150  2024-10-31T10:23:00Z                 1  2024-10-31T10:23:00Z
4           150  2024-10-31T10:23:00Z                 1  2024-10-31T10:21:00Z
5           150  2024-10-31T10:18:00Z                 1  2024-10-31T10:18:00Z
6            50  2024-10-31T07:15:00Z                 1  2024-10-30T21:48:00Z
7            50  2024-10-30T19:57:00Z                 1  2024-10-30T19:56:00Z
8            50  2024-10-30T19:53:00Z                 1  2024-10-30T19:53:00Z
9            50  2024-10-30T19:52:00Z                 1  2024-10-30T19:52:00Z

   SubmissionStatusTypeID GeneralComments DataProvidersReference  \
0                     200             NaN                    NaN
1                     200             NaN                    NaN
2                     200             NaN                    NaN
3                     200             NaN                    NaN
4                     200             NaN                    NaN
5                     200             NaN                    NaN
6                     200             NaN                    NaN
7                     200             NaN                    NaN
8                     200             NaN                    NaN
9                     200             NaN                    NaN

  OperatorsReference
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
5                NaN
6                NaN
7                NaN
8                NaN
9                NaN
Columnas en el DataFrame: Index(['IsRecentlyVerified', 'DateLastVerified', 'ID', 'UUID',
       'DataProviderID', 'OperatorID', 'UsageTypeID', 'UsageCost',
       'AddressInfo', 'Connections', 'NumberOfPoints', 'StatusTypeID',
       'DateLastStatusUpdate', 'DataQualityLevel', 'DateCreated',
       'SubmissionStatusTypeID', 'GeneralComments', 'DataProvidersReference',
       'OperatorsReference'],
      dtype='object')

In [17]:
data_chargesmap.head(10)

,IsRecentlyVerified,DateLastVerified,ID,UUID,DataProviderID,OperatorID,UsageTypeID,UsageCost,AddressInfo,Connections,NumberOfPoints,StatusTypeID,DateLastStatusUpdate,DataQualityLevel,DateCreated,SubmissionStatusTypeID,GeneralComments,DataProvidersReference,OperatorsReference
0,True,2024-10-31T10:57:00Z,305793,9F6D0CBB-087F-4263-9CF2-D78E4EFA6E0A,1,45.0,5.0,"1,7€/kWh","{'ID': 306182, 'Title': 'Padle Madrid Las Tabl...","[{'ID': 578690, 'ConnectionTypeID': 25, 'Statu...",2.0,50,2024-10-31T10:57:00Z,1,2024-10-31T10:57:00Z,200,NaN,NaN,NaN
1,True,2024-10-31T10:29:00Z,305791,8120149D-2C43-42F0-85F3-17240E5A760D,1,1.0,1.0,,"{'ID': 306180, 'Title': 'Ayunt. Yaiza. Uga. Ca...","[{'ID': 578688, 'ConnectionTypeID': 25, 'Statu...",2.0,150,2024-10-31T10:29:00Z,1,2024-10-31T10:29:00Z,200,NaN,NaN,NaN
2,True,2024-10-31T10:25:00Z,305790,4A210801-73B5-416D-A32B-56E6D638A142,1,1.0,1.0,,"{'ID': 306179, 'Title': 'Ayunt. Yaiza. Calle P...","[{'ID': 578687, 'ConnectionTypeID': 25, 'Statu...",2.0,150,2024-10-31T10:25:00Z,1,2024-10-31T10:25:00Z,200,NaN,NaN,NaN
3,True,2024-10-31T10:23:00Z,305789,AA61D61E-8DD1-4ACC-8497-7622B965DC5C,1,1.0,1.0,,"{'ID': 306178, 'Title': 'Ayunt. Yaiza. Calle J...","[{'ID': 578686, 'ConnectionTypeID': 25, 'Statu...",2.0,150,2024-10-31T10:23:00Z,1,2024-10-31T10:23:00Z,200,NaN,NaN,NaN
4,True,2024-10-31T10:23:00Z,305788,A65E27CE-36CB-410A-922A-D0DF6534BD30,1,1.0,1.0,,"{'ID': 306177, 'Title': 'Ayunt. Yaiza. Calle M...","[{'ID': 578685, 'ConnectionTypeID': 25, 'Statu...",2.0,150,2024-10-31T10:23:00Z,1,2024-10-31T10:21:00Z,200,NaN,NaN,NaN
5,True,2024-10-31T10:18:00Z,305787,30001948-0CA9-4E19-8143-6E8A2D4AABDA,1,1.0,1.0,,"{'ID': 306176, 'Title': 'Ayunt. Yaiza. Calle L...","[{'ID': 578684, 'ConnectionTypeID': 25, 'Statu...",2.0,150,2024-10-31T10:18:00Z,1,2024-10-31T10:18:00Z,200,NaN,NaN,NaN
6,True,2024-10-31T07:15:00Z,305785,0F9F3879-8DE6-4B0E-817A-D09607F796C5,1,207.0,4.0,"0,39€/kWh AC + parking fee","{'ID': 306174, 'Title': 'Parking La Mota Vieja...","[{'ID': 578677, 'ConnectionTypeID': 25, 'Statu...",8.0,50,2024-10-31T07:15:00Z,1,2024-10-30T21:48:00Z,200,NaN,NaN,NaN
7,True,2024-10-30T19:57:00Z,305784,33A3D719-A644-49A0-A1EA-B82A090F4A17,1,45.0,6.0,"0,25€/kWh","{'ID': 306173, 'Title': 'Rest. Hotel La Parada...","[{'ID': 578676, 'ConnectionTypeID': 25, 'Statu...",1.0,50,2024-10-30T19:57:00Z,1,2024-10-30T19:56:00Z,200,NaN,NaN,NaN
8,True,2024-10-30T19:53:00Z,305783,6B6006CD-D93D-469D-9278-A6F2C11F4F83,1,1.0,1.0,,"{'ID': 306172, 'Title': 'Gumiel de Izán', 'Add...","[{'ID': 578675, 'ConnectionTypeID': 25, 'Statu...",1.0,50,2024-10-30T19:53:00Z,1,2024-10-30T19:53:00Z,200,NaN,NaN,NaN
9,True,2024-10-30T19:52:00Z,305782,BD82D54E-AE15-4DDE-95A0-DFC24BC90CF6,1,3275.0,6.0,NaN,"{'ID': 306171, 'Title': 'Renault Aranda de Due...","[{'ID': 578674, 'ConnectionTypeID': 25, 'Statu...",2.0,50,2024-10-30T19:52:00Z,1,2024-10-30T19:52:00Z,200,NaN,NaN,NaN

In [18]:
data_chargesmap.drop(['IsRecentlyVerified','DateLastVerified','UUID','DataProviderID','OperatorID','UsageTypeID','NumberOfPoints','StatusTypeID','DateLastStatusUpdate','DataQualityLevel','DateCreated','SubmissionStatusTypeID','GeneralComments','DataProvidersReference','OperatorsReference'], axis=1, inplace=True)

In [19]:
data_chargesmap.head(10)

,ID,UsageCost,AddressInfo,Connections
0,305793,"1,7€/kWh","{'ID': 306182, 'Title': 'Padle Madrid Las Tabl...","[{'ID': 578690, 'ConnectionTypeID': 25, 'Statu..."
1,305791,,"{'ID': 306180, 'Title': 'Ayunt. Yaiza. Uga. Ca...","[{'ID': 578688, 'ConnectionTypeID': 25, 'Statu..."
2,305790,,"{'ID': 306179, 'Title': 'Ayunt. Yaiza. Calle P...","[{'ID': 578687, 'ConnectionTypeID': 25, 'Statu..."
3,305789,,"{'ID': 306178, 'Title': 'Ayunt. Yaiza. Calle J...","[{'ID': 578686, 'ConnectionTypeID': 25, 'Statu..."
4,305788,,"{'ID': 306177, 'Title': 'Ayunt. Yaiza. Calle M...","[{'ID': 578685, 'ConnectionTypeID': 25, 'Statu..."
5,305787,,"{'ID': 306176, 'Title': 'Ayunt. Yaiza. Calle L...","[{'ID': 578684, 'ConnectionTypeID': 25, 'Statu..."
6,305785,"0,39€/kWh AC + parking fee","{'ID': 306174, 'Title': 'Parking La Mota Vieja...","[{'ID': 578677, 'ConnectionTypeID': 25, 'Statu..."
7,305784,"0,25€/kWh","{'ID': 306173, 'Title': 'Rest. Hotel La Parada...","[{'ID': 578676, 'ConnectionTypeID': 25, 'Statu..."
8,305783,,"{'ID': 306172, 'Title': 'Gumiel de Izán', 'Add...","[{'ID': 578675, 'ConnectionTypeID': 25, 'Statu..."
9,305782,NaN,"{'ID': 306171, 'Title': 'Renault Aranda de Due...","[{'ID': 578674, 'ConnectionTypeID': 25, 'Statu..."

In [20]:
data_chargesmap['Address'] = data_chargesmap['AddressInfo'].apply(
    lambda x: f"{x.get('AddressLine1', '')}, {x.get('AddressLine2', '')}".strip(', ') if x else None)
data_chargesmap['Title'] = data_chargesmap['AddressInfo'].apply(lambda x: x.get('Title') if x else None)
data_chargesmap['Region'] = data_chargesmap['AddressInfo'].apply(lambda x: x.get('StateOrProvince') if x else None)
data_chargesmap['City'] = data_chargesmap['AddressInfo'].apply(lambda x: x.get('Town') if x else None)
data_chargesmap['PostalCode'] = data_chargesmap['AddressInfo'].apply(lambda x: x.get('Postcode') if x else None)
data_chargesmap['CountryID'] = data_chargesmap['AddressInfo'].apply(lambda x: x.get('CountryID') if x else None)

In [21]:
data_chargesmap.head(10)

,ID,UsageCost,AddressInfo,Connections,Address,Title,Region,City,PostalCode,CountryID
0,305793,"1,7€/kWh","{'ID': 306182, 'Title': 'Padle Madrid Las Tabl...","[{'ID': 578690, 'ConnectionTypeID': 25, 'Statu...",Avenida Camino de Santiago,Padle Madrid Las Tablas,Comunidad de Madrid,None,28050,210
1,305791,,"{'ID': 306180, 'Title': 'Ayunt. Yaiza. Uga. Ca...","[{'ID': 578688, 'ConnectionTypeID': 25, 'Statu...",Calle Joaquin Rodriguez,Ayunt. Yaiza. Uga. Calle Joaquin Rodriguez,None,None,None,210
2,305790,,"{'ID': 306179, 'Title': 'Ayunt. Yaiza. Calle P...","[{'ID': 578687, 'ConnectionTypeID': 25, 'Statu...","Calle Playa de Afre, Las Coloradas",Ayunt. Yaiza. Calle Playa de Afre,None,None,35770,210
3,305789,,"{'ID': 306178, 'Title': 'Ayunt. Yaiza. Calle J...","[{'ID': 578686, 'ConnectionTypeID': 25, 'Statu...","Avenida A Femes, Costa de Papagayo",Ayunt. Yaiza. Calle Janubio,None,None,35580,210
4,305788,,"{'ID': 306177, 'Title': 'Ayunt. Yaiza. Calle M...","[{'ID': 578685, 'ConnectionTypeID': 25, 'Statu...","Calle de la Rosa, Plan Parcial Playa Blanca",Ayunt. Yaiza. Calle Malvasía,None,None,35770,210
5,305787,,"{'ID': 306176, 'Title': 'Ayunt. Yaiza. Calle L...","[{'ID': 578684, 'ConnectionTypeID': 25, 'Statu...","Calle La Molina, Costa de Papagayo",Ayunt. Yaiza. Calle La Molina,None,None,35580,210
6,305785,"0,39€/kWh AC + parking fee","{'ID': 306174, 'Title': 'Parking La Mota Vieja...","[{'ID': 578677, 'ConnectionTypeID': 25, 'Statu...",Paseo de Soledad González,Parking La Mota Vieja Benavente,Castilla y León,Benavente,49600,210
7,305784,"0,25€/kWh","{'ID': 306173, 'Title': 'Rest. Hotel La Parada...","[{'ID': 578676, 'ConnectionTypeID': 25, 'Statu...",Calle Real,Rest. Hotel La Parada del Cid,Castilla y León,None,09610,210
8,305783,,"{'ID': 306172, 'Title': 'Gumiel de Izán', 'Add...","[{'ID': 578675, 'ConnectionTypeID': 25, 'Statu...",Carretera de Madrid,Gumiel de Izán,Castilla y León,None,None,210
9,305782,NaN,"{'ID': 306171, 'Title': 'Renault Aranda de Due...","[{'ID': 578674, 'ConnectionTypeID': 25, 'Statu...",N-1A,Renault Aranda de Duero,Castilla y León,Aranda de Duero,09400,210

In [22]:
data_chargesmap = data_chargesmap.reindex(columns=['ID','UsageCost','Address','Title', 'City','Region','PostalCode','CountryID', 'Connections','AddressInfo'])

In [23]:
data_chargesmap.head(10)

,ID,UsageCost,Address,Title,City,Region,PostalCode,CountryID,Connections,AddressInfo
0,305793,"1,7€/kWh",Avenida Camino de Santiago,Padle Madrid Las Tablas,None,Comunidad de Madrid,28050,210,"[{'ID': 578690, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306182, 'Title': 'Padle Madrid Las Tabl..."
1,305791,,Calle Joaquin Rodriguez,Ayunt. Yaiza. Uga. Calle Joaquin Rodriguez,None,None,None,210,"[{'ID': 578688, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306180, 'Title': 'Ayunt. Yaiza. Uga. Ca..."
2,305790,,"Calle Playa de Afre, Las Coloradas",Ayunt. Yaiza. Calle Playa de Afre,None,None,35770,210,"[{'ID': 578687, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306179, 'Title': 'Ayunt. Yaiza. Calle P..."
3,305789,,"Avenida A Femes, Costa de Papagayo",Ayunt. Yaiza. Calle Janubio,None,None,35580,210,"[{'ID': 578686, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306178, 'Title': 'Ayunt. Yaiza. Calle J..."
4,305788,,"Calle de la Rosa, Plan Parcial Playa Blanca",Ayunt. Yaiza. Calle Malvasía,None,None,35770,210,"[{'ID': 578685, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306177, 'Title': 'Ayunt. Yaiza. Calle M..."
5,305787,,"Calle La Molina, Costa de Papagayo",Ayunt. Yaiza. Calle La Molina,None,None,35580,210,"[{'ID': 578684, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306176, 'Title': 'Ayunt. Yaiza. Calle L..."
6,305785,"0,39€/kWh AC + parking fee",Paseo de Soledad González,Parking La Mota Vieja Benavente,Benavente,Castilla y León,49600,210,"[{'ID': 578677, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306174, 'Title': 'Parking La Mota Vieja..."
7,305784,"0,25€/kWh",Calle Real,Rest. Hotel La Parada del Cid,None,Castilla y León,09610,210,"[{'ID': 578676, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306173, 'Title': 'Rest. Hotel La Parada..."
8,305783,,Carretera de Madrid,Gumiel de Izán,None,Castilla y León,None,210,"[{'ID': 578675, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306172, 'Title': 'Gumiel de Izán', 'Add..."
9,305782,NaN,N-1A,Renault Aranda de Duero,Aranda de Duero,Castilla y León,09400,210,"[{'ID': 578674, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306171, 'Title': 'Renault Aranda de Due..."

In [24]:
data_chargesmap.rename(columns={'Title': 'Location'}, inplace=True)

In [25]:
data_chargesmap.head(10)

,ID,UsageCost,Address,Location,City,Region,PostalCode,CountryID,Connections,AddressInfo
0,305793,"1,7€/kWh",Avenida Camino de Santiago,Padle Madrid Las Tablas,None,Comunidad de Madrid,28050,210,"[{'ID': 578690, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306182, 'Title': 'Padle Madrid Las Tabl..."
1,305791,,Calle Joaquin Rodriguez,Ayunt. Yaiza. Uga. Calle Joaquin Rodriguez,None,None,None,210,"[{'ID': 578688, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306180, 'Title': 'Ayunt. Yaiza. Uga. Ca..."
2,305790,,"Calle Playa de Afre, Las Coloradas",Ayunt. Yaiza. Calle Playa de Afre,None,None,35770,210,"[{'ID': 578687, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306179, 'Title': 'Ayunt. Yaiza. Calle P..."
3,305789,,"Avenida A Femes, Costa de Papagayo",Ayunt. Yaiza. Calle Janubio,None,None,35580,210,"[{'ID': 578686, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306178, 'Title': 'Ayunt. Yaiza. Calle J..."
4,305788,,"Calle de la Rosa, Plan Parcial Playa Blanca",Ayunt. Yaiza. Calle Malvasía,None,None,35770,210,"[{'ID': 578685, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306177, 'Title': 'Ayunt. Yaiza. Calle M..."
5,305787,,"Calle La Molina, Costa de Papagayo",Ayunt. Yaiza. Calle La Molina,None,None,35580,210,"[{'ID': 578684, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306176, 'Title': 'Ayunt. Yaiza. Calle L..."
6,305785,"0,39€/kWh AC + parking fee",Paseo de Soledad González,Parking La Mota Vieja Benavente,Benavente,Castilla y León,49600,210,"[{'ID': 578677, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306174, 'Title': 'Parking La Mota Vieja..."
7,305784,"0,25€/kWh",Calle Real,Rest. Hotel La Parada del Cid,None,Castilla y León,09610,210,"[{'ID': 578676, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306173, 'Title': 'Rest. Hotel La Parada..."
8,305783,,Carretera de Madrid,Gumiel de Izán,None,Castilla y León,None,210,"[{'ID': 578675, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306172, 'Title': 'Gumiel de Izán', 'Add..."
9,305782,NaN,N-1A,Renault Aranda de Duero,Aranda de Duero,Castilla y León,09400,210,"[{'ID': 578674, 'ConnectionTypeID': 25, 'Statu...","{'ID': 306171, 'Title': 'Renault Aranda de Due..."

In [26]:
data_chargesmap.to_csv('data_chargesmap.csv', index=False)